server:
  port: 8080 # 注册中心占用8080端口

---

spring:
  application:
    name: eureka-server
  cloud:
    config:
      uri:  http://localhost:8888
---

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  #其实就是 http://localhost:8080/eureka/
    transport:
      retryableClientQuarantineRefreshPercentage: 1 #提升服务注册准确率
